import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 16,
        gap: 12,
    },
    userCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 14,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    userRow: {
        flexDirection: 'row',
        gap: 12,
        alignItems: 'center',
    },
    avatar: {
        width: 52,
        height: 52,
        borderRadius: 9999,
        backgroundColor: '#2563EB',
        justifyContent: 'center',
        alignItems: 'center',
    },
    avatarText: {
        color: '#FFFFFF',
        fontWeight: '700',
        fontSize: 18,
    },
    userName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#111827',
    },
    mailRow: {
        flexDirection: 'row',
        gap: 4,
        alignItems: 'center',
        marginTop: 2,
    },
    userMail: {
        fontSize: 13,
        color: '#6B7280',
    },
    badge: {
        marginTop: 4,
        backgroundColor: '#DBEAFE',
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 9999,
        alignSelf: 'flex-start',
    },
    badgeText: {
        fontSize: 11,
        color: '#1D4ED8',
        fontWeight: '500',
    },
    logoutBtn: {
        flexDirection: 'row',
        gap: 4,
        backgroundColor: '#FEE2E2',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 10,
    },
    logoutText: {
        color: '#DC2626',
        fontWeight: '500',
    },
    sectionHeader: {
        marginTop: 8,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#111827',
    },
    sectionSub: {
        fontSize: 13,
        color: '#6B7280',
    },
    addCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        padding: 12,
    },
    addTrigger: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    addTriggerText: {
        color: '#4B5563',
        fontSize: 13,
        fontWeight: '500',
    },
    addRow: {
        flexDirection: 'row',
        gap: 6,
    },
    input: {
        flex: 1,
        borderWidth: 1,
        borderColor: '#D1D5DB',
        borderRadius: 10,
        paddingHorizontal: 10,
        paddingVertical: 6,
        backgroundColor: '#FFFFFF',
    },
    primaryBtn: {
        backgroundColor: '#2563EB',
        borderRadius: 10,
        paddingHorizontal: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    primaryBtnText: {
        color: '#FFFFFF',
        fontWeight: '500',
    },
    secondaryBtn: {
        backgroundColor: '#F3F4F6',
        borderRadius: 10,
        paddingHorizontal: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    secondaryBtnText: {
        color: '#374151',
    },
    accountRow: {
        backgroundColor: '#FFFFFF',
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        padding: 12,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    accountLeft: {
        flexDirection: 'row',
        gap: 10,
        flex: 1,
        alignItems: 'center',
    },
    accountIcon: {
        width: 36,
        height: 36,
        borderRadius: 9999,
        backgroundColor: '#F3F4F6',
        justifyContent: 'center',
        alignItems: 'center',
    },
    accountName: {
        fontSize: 14,
        fontWeight: '600',
        color: '#111827',
    },
    accountMeta: {
        fontSize: 12,
        color: '#9CA3AF',
    },
    activePill: {
        marginLeft: 6,
        backgroundColor: '#DBEAFE',
        color: '#1D4ED8',
        paddingHorizontal: 6,
        paddingVertical: 1,
        borderRadius: 9999,
        fontSize: 11,
        overflow: 'hidden',
    },
    accountActions: {
        flexDirection: 'row',
        gap: 6,
    },
    switchBtn: {
        backgroundColor: '#2563EB',
        borderRadius: 9999,
        paddingHorizontal: 10,
        paddingVertical: 5,
    },
    switchBtnText: {
        color: '#FFFFFF',
        fontSize: 12,
        fontWeight: '500',
    },
    iconBtn: {
        padding: 6,
        borderRadius: 9999,
        backgroundColor: '#F3F4F6',
    },
    iconBtnSuccess: {
        padding: 6,
        borderRadius: 9999,
        backgroundColor: '#ECFDF3',
    },
    editRow: {
        flexDirection: 'row',
        gap: 4,
        alignItems: 'center',
    },
    editInput: {
        flex: 1,
        borderWidth: 1,
        borderColor: '#D1D5DB',
        borderRadius: 8,
        paddingHorizontal: 8,
        paddingVertical: 4,
        backgroundColor: '#FFFFFF',
    },
});
