import {StyleSheet} from "react-native";

export const styles = StyleSheet.create({
    // header: {
    //     marginBottom: 16,
    //     flexDirection: 'row',
    //     justifyContent: 'space-between',
    //     alignItems: 'center',
    // },
    // title: { fontSize: 18, fontWeight: '600', color: '#1F2937' },
    // subtitle: { fontSize: 13, color: '#6B7280', marginTop: 2 },
    // unscheduledBadge: {
    //     flexDirection: 'row',
    //     gap: 6,
    //     backgroundColor: '#FFFBEB',
    //     borderWidth: 1,
    //     borderColor: '#FDE68A',
    //     borderRadius: 12,
    //     paddingHorizontal: 10,
    //     paddingVertical: 6,
    //     alignItems: 'center',
    // },
    // unscheduledText: {
    //     color: '#B45309',
    //     fontSize: 12,
    //     fontWeight: '500',
    // },
    // horizontalScroll: {
    //     marginHorizontal: -16,
    //     paddingHorizontal: 16,
    // },
    // timelineRow: {
    //     flexDirection: 'row',
    //     gap: 0,
    //     borderWidth: 1,
    //     borderColor: '#E5E7EB',
    //     borderRadius: 12,
    //     overflow: 'hidden',
    // },
    // dayColumn: {
    //     width: 160,
    //     borderRightWidth: 1,
    //     borderRightColor: '#E5E7EB',
    //     backgroundColor: '#FFFFFF',
    // },
    // dayHeader: {
    //     paddingHorizontal: 12,
    //     paddingVertical: 10,
    //     backgroundColor: '#F9FAFB',
    //     borderBottomWidth: 1,
    //     borderBottomColor: '#E5E7EB',
    // },
    // dayWeek: {
    //     fontSize: 11,
    //     color: '#6B7280',
    //     textTransform: 'uppercase',
    //     letterSpacing: 0.6,
    // },
    // dayDate: {
    //     fontSize: 15,
    //     fontWeight: '600',
    //     color: '#1F2937',
    //     marginTop: 2,
    // },
    // dayBody: {
    //     padding: 10,
    //     minHeight: 200,
    // },
    // taskCard: {
    //     flexDirection: 'row',
    //     gap: 6,
    //     backgroundColor: '#FFFFFF',
    //     borderWidth: 1,
    //     borderColor: '#D1D5DB',
    //     borderRadius: 10,
    //     marginBottom: 6,
    //     borderLeftWidth: 4,
    //     shadowColor: '#000',
    //     shadowOpacity: 0.03,
    //     shadowOffset: { width: 0, height: 1 },
    //     shadowRadius: 2,
    // },
    // taskCardCompleted: {
    //     backgroundColor: '#F3F4F6',
    // },
    // taskCheck: {
    //     padding: 6,
    // },
    // taskInfo: {
    //     flex: 1,
    //     paddingVertical: 6,
    // },
    // taskName: {
    //     fontSize: 12,
    //     fontWeight: '500',
    //     color: '#1F2937',
    //     marginBottom: 2,
    // },
    // taskNameDone: {
    //     color: '#6B7280',
    //     textDecorationLine: 'line-through',
    // },
    // taskDates: {
    //     fontSize: 11,
    //     color: '#6B7280',
    // },
    // addDayButton: {
    //     borderWidth: 2,
    //     borderStyle: 'dashed',
    //     borderColor: '#D1D5DB',
    //     borderRadius: 10,
    //     paddingVertical: 8,
    //     marginTop: 6,
    //     alignItems: 'center',
    //     flexDirection: 'row',
    //     justifyContent: 'center',
    //     gap: 4,
    // },
    // addDayText: {
    //     fontSize: 11,
    //     color: '#6B7280',
    // },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,.4)',
        justifyContent: 'center',
        padding: 16,
    },
    modalCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        overflow: 'hidden',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
    },
    modalTitle: {
        fontSize: 16,
        fontWeight: '600',
    },
    closeButton: {
        padding: 4,
        borderRadius: 9999,
    },
    tabRow: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
    },
    tab: {
        flex: 1,
        paddingVertical: 10,
        alignItems: 'center',
    },
    tabActive: {
        backgroundColor: '#DBEAFE',
        borderBottomWidth: 2,
        borderBottomColor: '#2563EB',
    },
    tabInnerRow: {
        flexDirection: 'row',
        gap: 6,
        alignItems: 'center',
    },
    tabText: {
        fontSize: 13,
        color: '#6B7280',
    },
    tabTextActive: {
        color: '#2563EB',
        fontWeight: '600',
    },
    modalBody: {
        maxHeight: 360,
        paddingHorizontal: 16,
        paddingVertical: 14,
    },
    label: {
        fontSize: 13,
        fontWeight: '500',
        marginBottom: 4,
        color: '#374151',
    },
    input: {
        borderWidth: 1,
        borderColor: '#D1D5DB',
        borderRadius: 10,
        paddingHorizontal: 10,
        paddingVertical: 8,
        backgroundColor: '#FFFFFF',
        fontSize: 13,
    },
    priorityRow: {
        flexDirection: 'row',
        gap: 8,
    },
    priorityButton: {
        flex: 1,
        borderWidth: 2,
        borderColor: '#E5E7EB',
        borderRadius: 10,
        paddingVertical: 8,
        alignItems: 'center',
    },
    priorityButtonActiveLow: {
        borderColor: '#22C55E',
        backgroundColor: '#ECFDF3',
    },
    priorityButtonActiveMedium: {
        borderColor: '#F97316',
        backgroundColor: '#FFEDD5',
    },
    priorityButtonActiveHigh: {
        borderColor: '#EF4444',
        backgroundColor: '#FEE2E2',
    },
    priorityButtonText: {
        color: '#374151',
        fontWeight: '500',
    },
    priorityButtonTextActive: {
        color: '#111827',
    },
    dateRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    modalFooter: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 8,
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
        backgroundColor: '#F9FAFB',
        borderBottomLeftRadius: 16,
        borderBottomRightRadius: 16,
    },
    secondaryBtn: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 10,
        backgroundColor: '#E5E7EB',
    },
    secondaryBtnText: {
        fontWeight: '500',
        color: '#374151',
    },
    primaryBtn: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 10,
        backgroundColor: '#2563EB',
    },
    primaryBtnDisabled: {
        backgroundColor: '#93C5FD',
    },
    primaryBtnText: {
        color: '#FFFFFF',
        fontWeight: '600',
    },
    existingList: {
        maxHeight: 160,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 10,
        padding: 6,
        gap: 6,
    },
    existingItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingVertical: 6,
        paddingHorizontal: 8,
        borderWidth: 2,
        borderColor: '#E5E7EB',
        borderRadius: 8,
    },
    existingItemActive: {
        borderColor: '#2563EB',
        backgroundColor: '#DBEAFE',
    },
    existingItemText: {
        fontSize: 13,
        color: '#111827',
    },
    priorityPill: {
        borderWidth: 1,
        borderRadius: 9999,
        paddingHorizontal: 6,
        paddingVertical: 2,
    },
    priorityPillText: {
        fontSize: 10,
        fontWeight: '500',
        textTransform: 'capitalize',
    },
    emptyUnscheduled: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 24,
        gap: 6,
    },
    emptyUnscheduledTitle: {
        fontSize: 13,
        fontWeight: '500',
        color: '#374151',
    },
    emptyUnscheduledSubtitle: {
        fontSize: 11,
        color: '#6B7280',
    },
});
