import {StyleSheet} from "react-native";

export const styles = StyleSheet.create({
    header: {
        marginBottom: 16,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    title: { fontSize: 18, fontWeight: '600', color: '#1F2937' },
    subtitle: { fontSize: 13, color: '#6B7280', marginTop: 2 },
    unscheduledBadge: {
        flexDirection: 'row',
        gap: 6,
        backgroundColor: '#FFFBEB',
        borderWidth: 1,
        borderColor: '#FDE68A',
        borderRadius: 12,
        paddingHorizontal: 10,
        paddingVertical: 6,
        alignItems: 'center',
    },
    unscheduledText: {
        color: '#B45309',
        fontSize: 12,
        fontWeight: '500',
    },
    horizontalScroll: {
        marginHorizontal: -16,
        paddingHorizontal: 16,
    },
    timelineRow: {
        flexDirection: 'row',
        gap: 0,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 12,
        overflow: 'hidden',
    },
    dayColumn: {
        width: 160,
        borderRightWidth: 1,
        borderRightColor: '#E5E7EB',
        backgroundColor: '#FFFFFF',
    },
    dayHeader: {
        paddingHorizontal: 12,
        paddingVertical: 10,
        backgroundColor: '#F9FAFB',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
    },
    dayWeek: {
        fontSize: 11,
        color: '#6B7280',
        textTransform: 'uppercase',
        letterSpacing: 0.6,
    },
    dayDate: {
        fontSize: 15,
        fontWeight: '600',
        color: '#1F2937',
        marginTop: 2,
    },
    dayBody: {
        padding: 10,
        minHeight: 200,
    },
    taskCard: {
        flexDirection: 'row',
        gap: 6,
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#D1D5DB',
        borderRadius: 10,
        marginBottom: 6,
        borderLeftWidth: 4,
        shadowColor: '#000',
        shadowOpacity: 0.03,
        shadowOffset: { width: 0, height: 1 },
        shadowRadius: 2,
    },
    taskCardCompleted: {
        backgroundColor: '#F3F4F6',
    },
    taskCheck: {
        padding: 6,
    },
    taskInfo: {
        flex: 1,
        paddingVertical: 6,
    },
    taskName: {
        fontSize: 12,
        fontWeight: '500',
        color: '#1F2937',
        marginBottom: 2,
    },
    taskNameDone: {
        color: '#6B7280',
        textDecorationLine: 'line-through',
    },
    taskDates: {
        fontSize: 11,
        color: '#6B7280',
    },
    addDayButton: {
        borderWidth: 2,
        borderStyle: 'dashed',
        borderColor: '#D1D5DB',
        borderRadius: 10,
        paddingVertical: 8,
        marginTop: 6,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 4,
    },
    addDayText: {
        fontSize: 11,
        color: '#6B7280',
    },
});
