import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    scroll: {
        flex: 1,
    },
    scrollContent: {
        paddingHorizontal: 24,
        paddingVertical: 16,
    },
    container: {
        width: '100%',
        maxWidth: 640,
        alignSelf: 'center',
    },
    profileCard: {
        backgroundColor: '#ffffff',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#e5e7eb',
        padding: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 8,
        elevation: 3,
    },
    profileRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    profileLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        flexShrink: 1,
    },
    avatar: {
        width: 64,
        height: 64,
        borderRadius: 999,
        backgroundColor: '#2563eb',
        alignItems: 'center',
        justifyContent: 'center',
    },
    avatarText: {
        fontSize: 28,
        fontWeight: '700',
        color: '#ffffff',
    },
    profileName: {
        fontSize: 18,
        fontWeight: '600',
        color: '#111827',
    },
    row: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginTop: 2,
    },
    profileEmail: {
        fontSize: 13,
        color: '#4b5563',
    },
    providerBadge: {
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 999,
        backgroundColor: '#dbeafe',
        color: '#1d4ed8',
        fontSize: 11,
        fontWeight: '600',
    },
    logoutButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 10,
        backgroundColor: '#fef2f2',
    },
    logoutText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#b91c1c',
    },
    sectionHeader: {
        marginBottom: 12,
        marginTop: 8,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#111827',
        marginBottom: 4,
    },
    sectionSubtitle: {
        fontSize: 13,
        color: '#4b5563',
    },
    card: {
        backgroundColor: '#ffffff',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#e5e7eb',
        padding: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOpacity: 0.03,
        shadowOffset: { width: 0, height: 3 },
        shadowRadius: 6,
        elevation: 2,
    },
    cardHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    cardHeaderIcon: {
        marginRight: 8,
    },
    cardHeaderTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: '#111827',
    },
    addRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    addInput: {
        flex: 1,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#d1d5db',
        paddingHorizontal: 12,
        paddingVertical: 8,
        fontSize: 14,
        color: '#111827',
        backgroundColor: '#ffffff',
    },
    addConfirmButton: {
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 10,
        backgroundColor: '#2563eb',
    },
    addConfirmText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#ffffff',
    },
    addCancelButton: {
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 10,
        backgroundColor: '#f3f4f6',
    },
    addCancelText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#374151',
    },
    addTrigger: {
        borderRadius: 12,
        borderWidth: 2,
        borderStyle: 'dashed',
        borderColor: '#d1d5db',
        paddingVertical: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    addTriggerText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#4b5563',
    },
    listCard: {
        backgroundColor: '#ffffff',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#e5e7eb',
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOpacity: 0.03,
        shadowOffset: { width: 0, height: 3 },
        shadowRadius: 6,
        elevation: 2,
    },
    listHeader: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: '#f9fafb',
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
    },
    listHeaderTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: '#111827',
    },
    emptyState: {
        paddingVertical: 32,
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#6b7280',
        marginTop: 8,
        marginBottom: 2,
    },
    emptySubtitle: {
        fontSize: 13,
        color: '#9ca3af',
    },
    accountRow: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    accountRowActive: {
        backgroundColor: '#eff6ff',
    },
    accountRowDivider: {
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
    },
    accountLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        minWidth: 0,
    },
    accountAvatar: {
        width: 40,
        height: 40,
        borderRadius: 999,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    accountAvatarActive: {
        backgroundColor: '#dbeafe',
    },
    accountAvatarInactive: {
        backgroundColor: '#f3f4f6',
    },
    accountTextContainer: {
        flex: 1,
        minWidth: 0,
    },
    accountTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    accountName: {
        fontSize: 14,
        fontWeight: '500',
        color: '#111827',
        flexShrink: 1,
    },
    activeBadge: {
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 999,
        backgroundColor: '#dbeafe',
        color: '#1d4ed8',
        fontSize: 11,
        fontWeight: '600',
    },
    accountMeta: {
        marginTop: 2,
        fontSize: 12,
        color: '#6b7280',
    },
    accountActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginLeft: 8,
    },
    switchButton: {
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 10,
        backgroundColor: '#eff6ff',
    },
    switchButtonText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#2563eb',
    },
    iconButton: {
        padding: 6,
        borderRadius: 10,
    },
    iconButtonSuccess: {
        padding: 6,
        borderRadius: 10,
        backgroundColor: '#ecfdf3',
    },
    iconButtonNeutral: {
        padding: 6,
        borderRadius: 10,
        backgroundColor: '#f3f4f6',
    },
    editRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    editInput: {
        flex: 1,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#d1d5db',
        paddingHorizontal: 10,
        paddingVertical: 6,
        fontSize: 13,
        color: '#111827',
        backgroundColor: '#ffffff',
    },
})
